version: "3.8"

networks:
  tpo_notificationappapp_network:

services:
  tpo_notification_app:
    build:
      context: .
      dockerfile: ./backend/DockerfileAPI
    depends_on:
      - tpo_notification_redis
    ports:
      - "9091:9091"
    environment:
      - REDIS_HOST=tpo_notification_redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app
    networks:
      - tpo_notificationappapp_network

  tpo_notification_redis:
    image: "redis:alpine"
    ports:
      - "6388:6379"
    networks:
      - tpo_notificationappapp_network
